server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/config_db
    password: 1234
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

database-connection:
  data-sources:
    - name: first-db
      url: jdbc:postgresql://localhost:5432/first_db
      table: users
      user: postgres
      password: 1234
      mapping:
        id: id
        username: username
        name: name
        surname: surname
    - name: second-db
      url: jdbc:postgresql://localhost:5432/second_db
      table: users
      user: postgres
      password: 1234
      mapping:
        id: user_id
        username: login
        name: first_name
        surname: last_name

springdoc:
  api-docs:
    path: /api-docs
